# Generated by Django 3.2.6 on 2021-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='adminname',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
