# Generated by Django 3.2.6 on 2021-09-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_admin_adminname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='name',
            new_name='username',
        ),
    ]
