# Generated by Django 3.2.6 on 2021-09-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellname', models.CharField(max_length=50)),
                ('selladdress', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=50)),
                ('sellmobile', models.CharField(max_length=50)),
                ('sellusername', models.CharField(max_length=50)),
                ('sellpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
