# Generated by Django 3.2.6 on 2021-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=50)),
                ('phone_no', models.BigIntegerField()),
                ('username', models.CharField(blank='True', default='No Name', max_length=50)),
                ('password', models.CharField(blank='True', default='No Name', max_length=50)),
            ],
        ),
    ]
